services:
  mariadb:
    image: mariadb:10.11
    container_name: wheretopop-mariadb
    restart: always
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      TZ: ${TZ}
    ports:
      - "${DB_PORT}:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-p${MYSQL_ROOT_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 5

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.3
    container_name: wheretopop-elasticsearch
    env_file:
      - .env
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - bootstrap.memory_lock=true
      - ES_JAVA_OPTS=${ES_JAVA_OPTS}
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    ports:
      - "${ES_PORT}:9200"
      - "9300:9300"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9200"]
      interval: 10s
      timeout: 5s
      retries: 5

  kibana:
    image: docker.elastic.co/kibana/kibana:8.11.3
    container_name: wheretopop-kibana
    env_file:
      - .env
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "5601:5601"
    depends_on:
      elasticsearch:
        condition: service_healthy

  dbgate:
    image: dbgate/dbgate:latest
    container_name: wheretopop-dbgate
    restart: always
    environment:
      CONNECTIONS: mariadb
      LABEL_mariadb: MariaDB
      SERVER_mariadb: mariadb
      USER_mariadb: ${MYSQL_USER}
      PASSWORD_mariadb: ${MYSQL_PASSWORD}
      PORT_mariadb: ${DB_PORT}
      DATABASE_mariadb: ${MYSQL_DATABASE}
      ENGINE_mariadb: mysql@dbgate-plugin-mysql
    ports:
      - "8082:3000"
    volumes:
      - dbgate_data:/root/.dbgate
    depends_on:
      mariadb:
        condition: service_healthy

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: wheretopop-api
    restart: always
    env_file:
      - .env
    ports:
      - "${API_PORT:-8080}:8080"
    depends_on:
      mariadb:
        condition: service_healthy
      elasticsearch:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mariadb_data:
    driver: local
  elasticsearch_data:
    driver: local
  dbgate_data:
    driver: local
