spring:
  application:
    name: wheretopop-api
  profiles:
    active: ${ACTIVE_PROFILE:dev}
  r2dbc:
    url: r2dbc:mariadb://${DB_HOST:localhost}:${DB_PORT:3306}/${MYSQL_DATABASE:wheretopop}?useSSL=false&serverTimezone=UTC&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
    username: ${MYSQL_USER:root}
    password: ${MYSQL_PASSWORD:password}
    pool:
      initial-size: 5
      max-size: 10
      max-idle-time: 30m
  data:
    r2dbc:
      repositories:
        enabled: true
  elasticsearch:
    uris: http://${ES_HOST:localhost}:${ES_PORT:9200}

server:
  port: ${APP_PORT:8080}
  forward-headers-strategy: native
